name: HW1_performance

on:
  push

jobs:
  test:
    runs-on:
      group: runners_v1
    steps:
      - name: Use Go = 1.23
        uses: actions/setup-go@v3
        with:
          go-version: "=1.23"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # Pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}

      - name: Test HW1 Performance
        if: always()
        run: |
          set -euo pipefail
          make test_bench_hw1 2>&1 | tee ./${{ github.run_attempt }}/goperf-hw1.log | gotestfmt
        env:
          GLOG: no
          BINLOG: no
          HTTPLOG: no
          JSONIFY: "-json"

      # Upload formatted logs
      - name: Upload HW1 performance test log
        uses: actions/upload-artifact@v4
        with:
          name: perf-test-hw1-log
          path: ./${{ github.run_attempt }}/goperf-hw1.log
          if-no-files-found: error
